import type { InsertItemKindInput } from "../../engine/stock/items-repo.js";

/**
 * The easter-egg catalogue — show-specific dodgy stock that occasionally
 * surfaces in pools. Each item carries the original flaw text as flavour
 * (logged on spawn), a flaw_type so future systems can react, and a low
 * spawn_weight so they're rare. Episode references are kept as comments
 * for fans rather than as engine state.
 *
 * Per the design ladder: v1 only USES flavour_text + spawn_weight + the
 * easter-egg flag at the mechanic layer. flaw_type / risk / targetCustomers
 * are data-only; the inspection / heat / customer-fit systems will read
 * them later.
 */
export const EASTER_EGG_ITEMS: readonly InsertItemKindInput[] = [
  // S1E1 Big Brother
  {
    code: "ee-vinyl-briefcases",
    displayName: "Old English vinyl combination briefcases",
    category: "luggage",
    baseValue: 200,
    flawType: "faulty",
    risk: 4,
    targetCustomers: ["tradesmen", "businesses"],
    isEasterEgg: true,
    flavourText: "Combination locks have the codes sealed inside the cases — only a safe-cracker can open them. Also rejects, also nicked.",
    spawnWeight: 1,
  },
  // S1E2 Go West Young Man
  {
    code: "ee-clapped-out-car",
    displayName: "Clapped-out motor",
    category: "vehicles",
    baseValue: 50,
    flawType: "dangerous",
    risk: 5,
    targetCustomers: ["market-punters"],
    isEasterEgg: true,
    flavourText: "Brakes don't work. Rodney almost crashed it on the test drive.",
    spawnWeight: 1,
  },
  // S1E3 Cash and Curry
  {
    code: "ee-kubera-statue",
    displayName: "Porcelain statuette of Kubera",
    category: "decor",
    baseValue: 2000,
    flawType: "scam_bait",
    risk: 5,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "The 'priceless' statue is worth £17 on Portobello Road. Mr Ram doesn't exist.",
    spawnWeight: 1,
  },
  // S1E6 The Russians Are Coming
  {
    code: "ee-lead-fallout",
    displayName: "Boxes of lead from a fallout shelter",
    category: "tools",
    baseValue: 50,
    flawType: "stolen",
    risk: 4,
    targetCustomers: ["specialists", "tradesmen"],
    isEasterEgg: true,
    flavourText: "Originally meant for a DIY nuclear fallout shelter. Heavy, suspicious, hard to shift.",
    spawnWeight: 1,
  },
  // S2E3 A Losing Streak
  {
    code: "ee-fake-perfume",
    displayName: "'Yves Saint Dior' Parfum de Toilette",
    category: "novelty",
    baseValue: 20,
    flawType: "fake",
    risk: 3,
    targetCustomers: ["market-punters"],
    isEasterEgg: true,
    flavourText: "A bath tub of vile yellow liquid decanted into branded bottles in the lounge. Grandad stamps the boxes.",
    spawnWeight: 1,
  },
  // S2E5 The Yellow Peril
  {
    code: "ee-luminous-paint",
    displayName: "'Awayday Gold' luminous yellow paint",
    category: "tools",
    baseValue: 40,
    flawType: "stolen",
    risk: 5,
    targetCustomers: ["tradesmen"],
    isEasterEgg: true,
    flavourText: "Nicked from Clapham Junction. Used for railway tunnel signs because it glows in the dark.",
    spawnWeight: 1,
  },
  {
    code: "ee-diving-watches",
    displayName: "Deep-sea diver's watches",
    category: "electrical",
    baseValue: 30,
    flawType: "faulty",
    risk: 3,
    targetCustomers: ["yuppies", "businesses"],
    isEasterEgg: true,
    flavourText: "Tells the time in every capital city in the world — except London.",
    spawnWeight: 1,
  },
  // S3E2 Healthy Competition
  {
    code: "ee-lawnmower-engines",
    displayName: "Broken lawnmower engines",
    category: "tools",
    baseValue: 40,
    flawType: "faulty",
    risk: 5,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "Rusted and broken — bought drunk down the One-Eleven Club. Scrap value about £20.",
    spawnWeight: 1,
  },
  {
    code: "ee-yap-dogs",
    displayName: "Battery-powered toy yap-yap dogs",
    category: "toys",
    baseValue: 15,
    flawType: "faulty",
    risk: 2,
    targetCustomers: ["families", "market-punters"],
    isEasterEgg: true,
    flavourText: "Cheap, naff, and you have to leg it the moment you see Old Bill.",
    spawnWeight: 1,
  },
  {
    code: "ee-fire-alarms",
    displayName: "Smoke-damaged industrial fire alarms",
    category: "safety",
    baseValue: 80,
    flawType: "faulty",
    risk: 4,
    targetCustomers: ["businesses"],
    isEasterEgg: true,
    flavourText: "Industrial models, all 'guaranteed — sort of — to be in perfect working order'.",
    spawnWeight: 1,
  },
  // S3E3 Friday the 14th
  {
    code: "ee-poached-salmon",
    displayName: "Fresh-caught Cornish salmon",
    category: "food",
    baseValue: 5,
    flawType: "stolen",
    risk: 4,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "Poached from a private estate, with bribes to a corrupt gamekeeper. Plus an axe murderer's loose in the area.",
    spawnWeight: 1,
  },
  // S4E3 Hole in One
  {
    code: "ee-suntan-lotion",
    displayName: "Sun-tan lotion",
    category: "novelty",
    baseValue: 50,
    flawType: "wrong_season",
    risk: 3,
    targetCustomers: ["market-punters"],
    isEasterEgg: true,
    flavourText: "Flogged in cold weather. Eventually has to be knocked out to cover Albert's stunt-man losses.",
    spawnWeight: 1,
  },
  // S4E4 It's Only Rock and Roll
  {
    code: "ee-kandy-dolls",
    displayName: "Kandy Dolls",
    category: "toys",
    baseValue: 80,
    flawType: "faulty",
    risk: 3,
    targetCustomers: ["specialists", "families"],
    isEasterEgg: true,
    flavourText: "Each doll has a different voice chip meant for another toy entirely.",
    spawnWeight: 1,
  },
  // S5E1 From Prussia With Love
  {
    code: "ee-nomad-phones",
    displayName: "Nomad cordless mobile telephones",
    category: "electrical",
    baseValue: 100,
    flawType: "faulty",
    risk: 3,
    targetCustomers: ["yuppies"],
    isEasterEgg: true,
    flavourText: "Crackle, drop calls, generally useless. Still trying to flog them in the Nag's Head.",
    spawnWeight: 1,
  },
  // S5E4 Tea for Three
  {
    code: "ee-home-solarium",
    displayName: "Ultraviolet home solarium",
    category: "electrical",
    baseValue: 60,
    flawType: "wrong_market",
    risk: 2,
    targetCustomers: ["yuppies"],
    isEasterEgg: true,
    flavourText: "Retails at £375 'normally'. Comes with a free plug-in telephone if you'll just take it.",
    spawnWeight: 1,
  },
  // 1987 Christmas: The Frog's Legacy
  {
    code: "ee-rajah-computers",
    displayName: "Rajah 2000 home computers",
    category: "electrical",
    baseValue: 200,
    flawType: "fake",
    risk: 3,
    targetCustomers: ["families", "specialists"],
    isEasterEgg: true,
    flavourText: "BBC Masters in third-party Viglen cases with a stick-on badge. Flogged one to a vicar.",
    spawnWeight: 1,
  },
  // S6E2 Danger UXD
  {
    code: "ee-inflatable-dolls",
    displayName: "Lusty Linda & Erotic Estelle inflatable dolls",
    category: "novelty",
    baseValue: 50,
    flawType: "dangerous",
    risk: 5,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "Filled with explosive propane gas due to a factory mix-up. Self-inflate. Will detonate if heated.",
    spawnWeight: 1,
  },
  {
    code: "ee-continental-vcrs",
    displayName: "Video recorders (continental current)",
    category: "electrical",
    baseValue: 800,
    flawType: "wrong_market",
    risk: 4,
    targetCustomers: ["yuppies", "businesses"],
    isEasterEgg: true,
    flavourText: "Continental current only. Won't run on British power without a transformer the size of a suitcase.",
    spawnWeight: 1,
  },
  {
    code: "ee-jersey-tomatoes",
    displayName: "'Fresh Jersey' tomatoes",
    category: "food",
    baseValue: 20,
    flawType: "fake",
    risk: 2,
    targetCustomers: ["market-punters"],
    isEasterEgg: true,
    flavourText: "Definitely not from Jersey. Trigger says they taste off.",
    spawnWeight: 1,
  },
  // S6E3 Chain Gang
  {
    code: "ee-gold-chains",
    displayName: "18-carat gold chains",
    category: "novelty",
    baseValue: 50,
    flawType: "scam_bait",
    risk: 5,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "Arnie fakes a heart attack mid-deal and escapes in a fake ambulance.",
    spawnWeight: 1,
  },
  // S6E5 Sickness and Wealth
  {
    code: "ee-summer-dresses",
    displayName: "Crimplene summer dresses",
    category: "clothing",
    baseValue: 200,
    flawType: "wrong_season",
    risk: 4,
    targetCustomers: ["old-dears"],
    isEasterEgg: true,
    flavourText: "Big flowers, flogged at the market through a February of frost and sleet.",
    spawnWeight: 1,
  },
  // S6E5/6 Mickey's mobiles
  {
    code: "ee-mickeys-mobiles",
    displayName: "Mobile phones (Mickey Pearce)",
    category: "electrical",
    baseValue: 200,
    flawType: "stolen",
    risk: 5,
    targetCustomers: ["yuppies"],
    isEasterEgg: true,
    flavourText: "Bring trouble with the Driscoll Brothers in the next episode.",
    spawnWeight: 1,
  },
  // 1989 Jolly Boys' Outing
  {
    code: "ee-albanian-radios",
    displayName: "Albanian car radios",
    category: "electrical",
    baseValue: 60,
    flawType: "dangerous",
    risk: 5,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "Catch fire. One fitted in the Jolly Boys' coach blew up near Margate.",
    spawnWeight: 1,
  },
  // 1991 Miami Twice
  {
    code: "ee-romanian-riesling",
    displayName: "Romanian Riesling",
    category: "food",
    baseValue: 80,
    flawType: "stolen",
    risk: 4,
    targetCustomers: ["businesses", "specialists"],
    isEasterEgg: true,
    flavourText: "Dodgy enough that he had to lay low and skip the country.",
    spawnWeight: 1,
  },
  // 1992 Mother Nature's Son
  {
    code: "ee-peckham-spring",
    displayName: "Peckham Spring mineral water",
    category: "food",
    baseValue: 50,
    flawType: "fake",
    risk: 3,
    targetCustomers: ["businesses", "market-punters"],
    isEasterEgg: true,
    flavourText: "It's tap water. Bottling plant is the lounge. Possibly contaminated.",
    spawnWeight: 1,
  },
  // 1996 Modern Men
  {
    code: "ee-mens-wigs",
    displayName: "Box of men's wigs",
    category: "clothing",
    baseValue: 80,
    flawType: "wrong_market",
    risk: 5,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "Thought he was buying ladies' wigs to flog to old dears in the Nag's Head. They are very much not.",
    spawnWeight: 1,
  },
  {
    code: "ee-clip-on-ponytails",
    displayName: "Clip-on ponytails",
    category: "clothing",
    baseValue: 30,
    flawType: "wrong_market",
    risk: 2,
    targetCustomers: ["yuppies"],
    isEasterEgg: true,
    flavourText: "Aimed at the trendy market. Rodney unwillingly becomes the model.",
    spawnWeight: 1,
  },
  // Pre-show legend
  {
    code: "ee-one-legged-turkeys",
    displayName: "One-legged turkeys",
    category: "food",
    baseValue: 20,
    flawType: "faulty",
    risk: 4,
    targetCustomers: ["families", "market-punters"],
    isEasterEgg: true,
    flavourText: "Sold from the back of the Reliant. Tin says it all.",
    spawnWeight: 1,
  },
  {
    code: "ee-gas-conversion-kits",
    displayName: "DIY North Sea gas conversion kits",
    category: "tools",
    baseValue: 40,
    flawType: "wrong_market",
    risk: 5,
    targetCustomers: ["tradesmen"],
    isEasterEgg: true,
    flavourText: "Sent Rodney with chickenpox to flog them on the Mountbatten Estate. Which is all-electric.",
    spawnWeight: 1,
  },
  // Various referenced
  {
    code: "ee-china-cats",
    displayName: "China cats playing 'How Much Is That Doggy in the Window'",
    category: "decor",
    baseValue: 15,
    flawType: "faulty",
    risk: 2,
    targetCustomers: ["old-dears"],
    isEasterEgg: true,
    flavourText: "A balls-up at the factory put the wrong chimes in. Cats playing a song about a dog.",
    spawnWeight: 1,
  },
  {
    code: "ee-singing-dolls",
    displayName: "'Made in Britain' singing dolls",
    category: "toys",
    baseValue: 80,
    flawType: "faulty",
    risk: 3,
    targetCustomers: ["families"],
    isEasterEgg: true,
    flavourText: "Sing a full repertoire of Chinese lullabies.",
    spawnWeight: 1,
  },
  {
    code: "ee-anthem-watches",
    displayName: "National-anthem digital watches",
    category: "electrical",
    baseValue: 50,
    flawType: "faulty",
    risk: 3,
    targetCustomers: ["specialists", "yuppies"],
    isEasterEgg: true,
    flavourText: "Play 36 different national anthems on the hour. Loudly.",
    spawnWeight: 1,
  },
  {
    code: "ee-skeet-cd-players",
    displayName: "Portable CD players",
    category: "electrical",
    baseValue: 60,
    flawType: "faulty",
    risk: 4,
    targetCustomers: ["music-fans", "yuppies"],
    isEasterEgg: true,
    flavourText: "Fling the discs out like clay pigeons.",
    spawnWeight: 1,
  },
  {
    code: "ee-paint-stripper-hairdryers",
    displayName: "Hairdryers (industrial)",
    category: "electrical",
    baseValue: 80,
    flawType: "faulty",
    risk: 4,
    targetCustomers: ["specialists"],
    isEasterEgg: true,
    flavourText: "Are actually paint strippers.",
    spawnWeight: 1,
  },
  {
    code: "ee-infrared-massagers",
    displayName: "Infra-red 'miracle-cure' body massagers",
    category: "electrical",
    baseValue: 60,
    flawType: "fake",
    risk: 3,
    targetCustomers: ["old-dears"],
    isEasterEgg: true,
    flavourText: "Hit the health market. They do not cure anything.",
    spawnWeight: 1,
  },
];
